singnet/das-atom-db

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/i_database.py, tests/adapters/test_ram_only.py
=> [# 19] FixBug / Add get_link_type method in InMemoryDB

hyperon_das_atomdb/__init__.py
Expose NodeDoesNotExistException
=> Quick fix for bug reported in #6

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/unit/adapters/test_ram_only.py
Resolves singnet/das-servless-functions#27
=> [servless-functions#27] Bugfix / Refactor get_atom

hyperon_das_atomdb/adapters/redis_mongo_db.py, tests/unit/adapters/test_redis_mongo_db.py
Deprecated code was left behind after https://github.com/singnet/das-atom-db/pull/66
Resolves #53
=> [53] Remove deprecated code

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py
Resolves #62 
Resolves singnet/das-query-engine-db#80
=> [#62] Add get_incoming_links

.github/workflows/testing.yml
=> ci: testing src on PR

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py
=> [#70] Change the return of method get_incomming_links

.github/workflows/publish-pypi.yml
* Add the changelog manually (this will be used in the message sent to the mattermost)
=> ci: manual changelog

hyperon_das_atomdb/adapters/redis_mongo_db.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_redis_mongo_db.py
=> [HOTFIX] Fixed mistakenly set method name

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py
=> [#78] Remove _build_named_type_template method

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py
=> [#46 #48] Add error log message to adapters and Implement (get_all_links) method

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/integration/adapters/animals_kb.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_ram_only.py
reindex() rebuilds inverted pattern index tables in Redis and in-ram hashtables
=> [#86] Implement reindex() in all AtomDB adapters

.github/workflows/publish-pypi.yml
=> [das-query-engine#127][das-query-engine#128] Fix mattermost message

README.md
* Add in README.md a link to github releases
Closes #82
=> [#82] Add AtomDB Release Notes

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, pyproject.toml
=> [#98] Refactor get_incoming_links() in all AtomDB adapters

CHANGELOG, hyperon_das_atomdb/adapters/redis_mongo_db.py, tests/integration/adapters/test_redis_mongo.py
=> [#100] Add support to MeTTa loader nodes/links mapping

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/integration/adapters/test_redis_mongo.py
=> [#102] Update get_matched_links(), get_matched_type_template() e get_matched_type()

hyperon_das_atomdb/__init__.py
Resolves singnet/das-query-engine#159
=> [das-query-engine#159] Add version in __init__.py file

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, tests/unit/adapters/test_ram_only.py
=> [#112] Fix return of the functions get_matched_links(), get_incoming_links(), get_matched_type_template(), get_matched_type() from set to list

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, hyperon_das_atomdb/index.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_redis_mongo_db.py
=> [#114] Add create_field_index() to RedisMongoDB adapter

CHANGELOG, hyperon_das_atomdb/adapters/redis_mongo_db.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_redis_mongo_db.py
=> [#120] Refactor collection in RedisMongoDB

CHANGELOG, hyperon_das_atomdb/adapters/redis_mongo_db.py
=> [#132] Fix bug in create_field_index() method

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py
Related to https://github.com/singnet/das-query-engine/issues/223
=> [das-query-engine#223] Update log messages

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_ram_only.py
Resolves singnet/das-query-engine#214
=> [das-query-engine#214] Add retrieve_all_documents()

CHANGELOG, hyperon_das_atomdb/adapters/redis_mongo_db.py, tests/unit/adapters/test_redis_mongo_db.py
=> [#124] Changed count_atoms() to return more accurate numbers

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_redis_mongo_db.py
Resolves singnet/das-query-engine#197
=> [das-query-engine#197] Changed get_all_links() to return a tuple

CHANGELOG, hyperon_das_atomdb/database.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_redis_mongo_db.py
=> [#142] Changed add_link() and add_node() to work with get_atom returns

.github/workflows/publish-pypi.yml
Closes https://github.com/singnet/das/issues/6
=> [das#6] Migrate contents of das-scripts-pipeline to das

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, tests/integration/adapters/test_redis_mongo.py
Resolves singnet/das-query-engine#114
=> [das-query-engine#114] Changed commit() to receive buffer as a kwargs parameter

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/unit/adapters/test_redis_mongo_db.py
=> Change MongoFieldNames to FieldNames

.github/workflows/publish-pypi.yml
=> [#125] Fix misleading message in das-atom-db building pipeline

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, hyperon_das_atomdb/index.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_redis_mongo_db.py
closes #153 
Removed 'field' from create index method
=> [#153] Refactoring create index

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py
Relates to https://github.com/singnet/das/issues/45
This is just the first PR of a series of changes refactoring RAM Only DAS.
The changes here will make easier the job of progressing on the overall refactoring work once PyCharm refactoring functionalities perform better when type annotations are well done.
- Fixing some type annotations.
- Standardizing strings quotes (`"` instead of `'`).
- Fixing some log messages.
=> [das#45] Round 1 - Initial refactoring of RAM Only DAS

.github/workflows/run-tests.yml, Makefile
Closes https://github.com/singnet/das/issues/51
=> [das#51] Add static analysis to the pipeline of the main repos

.github/workflows/publish-pypi.yml, .github/workflows/run-tests.yml
Closes https://github.com/singnet/das/issues/56
=> [#56] Review release process

.github/workflows/run-tests.yml
Closes https://github.com/singnet/das/issues/59
=> [#59] Separate Tests and Lint into Individual jobs on pipeline

hyperon_das_atomdb/__init__.py, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, hyperon_das_atomdb/exceptions.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py
Relates to singnet/das-query-engine#225
=> Replace NodeDoesNotExist and LinkDoesNotExist by AtomDoesNotExit

README.md, hyperon_das_atomdb/__init__.py, pyproject.toml
=> [#171] bumping up python to 3.10

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/database.py, hyperon_das_atomdb/index.py, hyperon_das_atomdb/logger.py
Refactors multiple files:
1. Fixes type annotations, following the new standard (`Optional[Dict[A, B]]` ⇒ `dict[A, B] | None`).
2. Left some `TODO` comments for future evaluation.
3. Eliminates a `while True` statement.
4. Ensures files pass green through `pylint`.
=> [#161] fixing small logic stuff

.black.cfg, .flake8.cfg, .github/workflows/run-tests.yml, .isort.cfg, Makefile
Closes https://github.com/singnet/das/issues/75
=> [das#75] Make sure all repos are using the same lint config

hyperon_das_atomdb/adapters/ram_only.py
=> [#199] [HOTFIX] Remove deep copy from ram_only.get_atom()

hyperon_das_atomdb/adapters/ram_only.py
=> [#201] InMemoryDB small improvements/cleanups

hyperon_das_atomdb_cpp/src/document_types.h, hyperon_das_atomdb_cpp/src/nanobind/hyperon_das_atomdb_cpp_bind.cc, hyperon_das_atomdb_cpp/src/utils/expression_hasher.h
Closes #231 
Found a few tiny issues after merging this PR: https://github.com/singnet/das-atom-db/pull/230
=> [#231] hotfixes

hyperon_das_atomdb_cpp/CMakeLists.txt, hyperon_das_atomdb_cpp/Makefile, hyperon_das_atomdb_cpp/docker/Dockerfile.glibc.wheeler, hyperon_das_atomdb_cpp/docker/Dockerfile.musl.wheeler, hyperon_das_atomdb_cpp/scripts/_build_glibc_wheel.sh, hyperon_das_atomdb_cpp/scripts/_build_musl_wheel.sh, hyperon_das_atomdb_cpp/scripts/build_glibc_wheeler_docker_image.sh, hyperon_das_atomdb_cpp/scripts/build_musl_wheeler_docker_image.sh, hyperon_das_atomdb_cpp/scripts/build_wheeler_docker_image.sh, hyperon_das_atomdb_cpp/scripts/common.sh, hyperon_das_atomdb_cpp/scripts/run_glibc_wheeler.sh, hyperon_das_atomdb_cpp/scripts/run_musl_wheeler.sh
=> [#250] building/publishing Alpine/MUSL module

hyperon_das_atomdb_cpp/scripts/_build_glibc_wheel.sh, hyperon_das_atomdb_cpp/scripts/_build_musl_wheel.sh, hyperon_das_atomdb_cpp/scripts/build_glibc_wheeler_docker_image.sh, hyperon_das_atomdb_cpp/scripts/build_musl_wheeler_docker_image.sh, hyperon_das_atomdb_cpp/scripts/common.sh, hyperon_das_atomdb_cpp/scripts/run_glibc_wheeler.sh, hyperon_das_atomdb_cpp/scripts/run_musl_wheeler.sh
=> [#253] [HOTFIX] fixing wheel build

cpp/nanobind/src/hyperon_das_atomdb_cpp_bind.cc, cpp/scripts/_build_glibc_packs.sh, cpp/scripts/_build_musl_packs.sh
=> [#260] suppressing suppresable leak warnings

.github/workflows/publish-pypi.yml, .github/workflows/run-tests.yml
Closes https://github.com/singnet/das/issues/169
=> [das#169]: Pin poetry version to avoid pipeline failures
