singnet/das-atom-db

hyperon_das_atomdb/__init__.py, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/adapters/server_db.py, hyperon_das_atomdb/database.py, hyperon_das_atomdb/utils/patterns.py, tests/unit/adapters/test_redis_mongo_db.py
AtomDB is no longer an interface as it contains concrete methods.
This is part of the work for https://github.com/singnet/das-atom-db/issues/43
=> Remove "i" prefix of i_database.py and IAtomDB

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/adapters/server_db.py, hyperon_das_atomdb/database.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py
This is required in order to implement #43 properly.
* Factored the commom code from redis_mongo and ram_only regarding add_node() and add_link() and moved it to the abstract superclass
* Made those method abstract in the superclass forcing their implementation in all adapters
* Implemented a stub version in ServerDB as well just raising an exception
=> Implement add_node() and add_link() in redis_mongo adapter

README.md, hyperon_das_atomdb/adapters/redis_mongo_db.py
The USE_CACHED variables were initially loading as 'none' values on the Vultr server due to their readiness just after the import of the file. To address this issue, I devised a class containing properties linked to the cache. As a result, the values are calculated only when necessary, ensuring the variables are ready for use precisely when needed.
=> fix: das atomdb cached

hyperon_das_atomdb/adapters/redis_mongo_db.py
"targets" were being wrongly added to node documents in get_atom_as_dict()
=> [HOTFIX] Prevents "targets" from being added in Node documents

hyperon_das_atomdb/database.py
Resolves #91 
Required by https://github.com/singnet/das-query-engine/issues/120
=> [HOTFIX] Add 'type' in documents returned by get_atom()

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, hyperon_das_atomdb/entity.py, tests/unit/adapters/test_ram_only.py
=> [#84 ] Add delete_atom method in the InMemoryDB adapter

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py
Changes:
- Add a private method to retrieve members set in Redis `_get_redis_members`
- Change the return of the methods `_retrieve_incoming_set`, `_retrieve_template`, `_retrieve_pattern`
- Change the `extra_parameters` parameter to `kwargs`
Resolves #96
=> [#96] Adjust retrieve methods for sets in Redis - incoming_set, templates, patterns

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, hyperon_das_atomdb/index.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_redis_mongo_db.py
=> [#118] Create a new set in Redis to save custom index filters

.github/workflows/pull-request.yml
Closes https://github.com/singnet/das/issues/16
=> [das#16] Remove integration tests from the workflows and add them at the end of the release script

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py
Added new parameter to count_atoms, the behavior was changed for count_atoms:
- Old:
- Returns the total number of nodes and links (slow)
- eg: (16, 24) 
- New
- Returns the total number of atoms (fast)
- eg: (40, 0)
=> [das#226] Add optional parameter to count atoms

.pylintrc, Makefile, pyproject.toml
Closes #169 
Adds a new target to `Makefile`, named `pylint`.
For now, `make pylint` must be executed manually. Once all code base is passing green through `pylint`, it must be added to the CI pipeline as well as to the `Makefile`'s `pre-commit` target.
=> [#169] adding pylint

hyperon_das_atomdb/database.py
Refactors `database.py`:
1. Applies `black` formatting.
2. Ensures lines width at max 100 chars.
3. Adds and fixes type annotations, mainly returns.
4. Applies new standard of type annotations (i.e. `dict[A, B] | None` instead of `Optional[Dict[A, B]]`.
5. Adds and/or fixes docstrings.
6. Ensures the file passes green through `pylint`.
=> [#161] refactoring `database.py`

hyperon_das_atomdb/__init__.py, hyperon_das_atomdb/adapters/__init__.py, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/exceptions.py, hyperon_das_atomdb/index.py, hyperon_das_atomdb/logger.py, hyperon_das_atomdb/utils/expression_hasher.py, hyperon_das_atomdb/utils/patterns.py, hyperon_das_atomdb/utils/settings.py
Refactors multiple files:
```
hyperon_das_atomdb/__init__.py
hyperon_das_atomdb/adapters/ram_only.py
hyperon_das_atomdb/adapters/__init__.py
hyperon_das_atomdb/exceptions.py
hyperon_das_atomdb/index.py
hyperon_das_atomdb/logger.py
hyperon_das_atomdb/utils/expression_hasher.py
hyperon_das_atomdb/utils/patterns.py
hyperon_das_atomdb/utils/settings.py
```
1. Applies `black` formatting.
2. Ensures lines width at max 100 chars.
3. Adds and fixes type annotations, mainly returns.
4. Applies new standard of type annotations (i.e. `dict[A, B] | None` instead of `Optional[Dict[A, B]]`.
5. Adds and/or fixes docstrings.
6. Ensures the files pass green through `pylint`.
7. Fixes some typos.
8. Left some `TODO` comments for future evaluation.
=> [#161] refactoring multiple small files

hyperon_das_atomdb/adapters/ram_only.py
Refactors `ram_only.py`:
1. Applies `black` formatting.
2. Ensures lines width at max 100 chars.
3. Adds and fixes type annotations, mainly returns.
4. Applies new standard of type annotations (i.e. `dict[A, B] | None` instead of `Optional[Dict[A, B]]`.
5. Adds and/or fixes docstrings.
6. Ensures the file passes green through `pylint`.
7. Fixes some typos.
8. Left some `TODO` comments for future evaluation.
=> [#161] refactoring `ram_only.py`

hyperon_das_atomdb/adapters/redis_mongo_db.py
Refactors `redis_mongo_db.py`:
1. Applies `black` formatting.
2. Ensures lines width at max 100 chars.
3. Adds and/or fixes type annotations, mainly returns.
4. Applies new standard of type annotations (i.e. `dict[A, B] | None` instead of `Optional[Dict[A, B]]`).
5. Adds and/or fixes docstrings.
6. Ensures the file passes green through `pylint`.
7. Fixes some typos.
8. Left some `TODO` comments for future evaluation.
9. Eliminates a `while True` statement.
=> [#161] refactoring `redis_mongo_db.py` and fixing small logic stuff

.github/workflows/publish-pypi.yml, .github/workflows/run-tests.yml
@andre-senna  In one of the recent updates, I changed the Ubuntu version from ubuntu-latest to ubuntu-20.04, but it should actually be ubuntu-22.04. This didn’t cause any issues because I also set the Python version in the pipeline, but I’m still updating to the correct Ubuntu version.
=> ci: update ubuntu to version 22.04

Makefile, mypy.ini, pyproject.toml
Adds a new target to `Makefile`, named `mypy`.
For now, `make mypy` must be executed manually. Once all code base is passing green through `mypy`, it must be added to the CI pipeline as well as to the `Makefile`'s `pre-commit` target.
=> [#161] adding `mypy` to the repo

Makefile, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/unit/adapters/test_ram_only.py
- Created some **Type Aliases**, like `AtomT: TypeAlias = dict[str, Any]`, similarly for `NodeT`, `NodeParamsT`, `LinkT` and `LinkParamsT`.
- Used the new type aliases for annotations on all over the code.
- Revisited and fixed all type hints with the help of `mypy`.
- Left some `TODO`s for future evaluation.
- Ensured that the entire repo passes green through `flake8` + `pylint` + `mypy`.
- Fixed a unit test.
- Improved docstrings.
=> [#161] fixing some returns and type hints

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py
Closes #182 
- Refactored the `AtomDB.get_atom` method and all code related to it, for example, the `get_incoming_links` method.
- Now, when both `no_target_format` is set to `False`and `targets_document` is set to `True` in `kwargs`, the `targets_document` will be included in the Atom dictionary as a sub-object instead of giving a different return type (`tuple`) as it was previously implemented.
- Revisited some type annotations and docstrings.
- Adapted unit tests which involve `get_atom`.
=> [#182] refactoring `AtomDB.get_atom`

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py
Closes #185
Refactored `AtomDB.get_matched_links` method and related code in order to simplify return types, as well as other methods with similar return types.
=> [#185] refactoring `AtomDB.get_matched_links` and related code

hyperon_das_atomdb/adapters/ram_only.py
Hotfix related to https://github.com/singnet/das-query-engine/issues/304
- Returning `kwargs.get('cursor')` where `None` was unconditionally being returned, no matter what.
=> [das-query-engine#304] returning the cursor that comes in kwargs

hyperon_das_atomdb/utils/expression_hasher.py, tests/unit/adapters/test_ram_only.py
Relates to #191 
Added a new test case, skipped for now, which must be enabled in the future once we get some refactorings done.
This is the error raised if the skip decorator is removed and a `make unit-tests` is executed:
```
>       _, links = database.get_matched_links('Connectivity', target_handles)
tests/unit/adapters/test_ram_only.py:483:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
hyperon_das_atomdb/adapters/ram_only.py:545: in get_matched_links
link_handle = self.get_link_handle(link_type, target_handles)
hyperon_das_atomdb/adapters/ram_only.py:494: in get_link_handle
link_handle = self.link_handle(link_type, target_handles)
hyperon_das_atomdb/database.py:123: in link_handle
return …
```
=> [#191] adding skipped test for future evaluation

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, hyperon_das_atomdb/utils/expression_hasher.py, pyproject.toml, tests/unit/adapters/test_ram_only_extra.py, tests/unit/adapters/test_redis_mongo_extra.py, tests/unit/fixtures.py, tests/unit/test_database.py
=> [#203] Review AtomDB tests

hyperon_das_atomdb/adapters/redis_mongo_db.py, tests/unit/test_database.py
_get_atom() were missing HANDLE and TYPE fields in returned document
=> [HOTFIX] Fix ill-committed  update in get_atom()

CHANGELOG, hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py, tests/unit/test_database.py
Resolves #216 
Required in the context of https://github.com/singnet/das-atom-db/issues/188
=> [#216]  Removed cursor from api of get_matched*() and get_incoming_links()

hyperon_das_atomdb/adapters/ram_only.py, tests/unit/adapters/test_ram_only.py
=> [#223] reverting erratic recent changes

hyperon_das_atomdb/adapters/ram_only.py, hyperon_das_atomdb/adapters/redis_mongo_db.py, hyperon_das_atomdb/database.py, tests/integration/adapters/test_redis_mongo.py, tests/unit/adapters/test_ram_only.py, tests/unit/adapters/test_redis_mongo_db.py, tests/unit/test_database.py
=> [#223] handling/using/returning `set` instead of `list` when possible

hyperon_das_atomdb/database.py, tests/integration/adapters/test_redis_mongo.py
AtomDB doesn't allow update atoms on the same transaction, to fix that we need to commit before update the atoms.
=> [FIX] Fixing unspected value returning in the test

hyperon_das_atomdb_cpp/CMakeLists.txt, hyperon_das_atomdb_cpp/deps/requirements.txt, hyperon_das_atomdb_cpp/docker/Dockerfile.wheel, hyperon_das_atomdb_cpp/requirements.txt, hyperon_das_atomdb_cpp/src/utils/expression_hasher.h
=> [#235] creating `deps` dir and updating build process

hyperon_das_atomdb_cpp/src/constants.cc, hyperon_das_atomdb_cpp/src/constants.h, hyperon_das_atomdb_cpp/src/database.cc, hyperon_das_atomdb_cpp/src/hyperon_das_atomdb_cpp/constants/__init__.py, hyperon_das_atomdb_cpp/src/hyperon_das_atomdb_cpp/database/__init__.py, hyperon_das_atomdb_cpp/src/nanobind/bind_helpers.h, hyperon_das_atomdb_cpp/src/nanobind/hyperon_das_atomdb_cpp_bind.cc
=> [#238] everything under submodules, moving `FieldNames` from python to c++

hyperon_das_atomdb_cpp/src/nanobind/hyperon_das_atomdb_cpp_bind.cc
=> [#240] making `Atom/Node/Link` attrs writable
